name: github-actions-python-app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: python test_hello.py

      - name: Notify us
        if: success()
        run: echo "Tests passed on Python ${{ matrix.python-version }}"

      - name: using secrets
        run: echo "this is the secret ${{secrets.MY_SECRET}}"

      - name: using secrets with environment varibales
        run: echo "this is an env secret- $MY_SECRET"
        env:
          MY_SECRET: ${{secrets.MY_SECRET}}
